sonar.projectKey=HugoEmDu_EntornoCICD
sonar.organization=hugoemdu

# Indicamos que analice los archivos de la raíz
sonar.sources=.

# Excluimos las pruebas y los paquetes para que no alteren las métricas de calidad
sonar.exclusions=**/node_modules/**,**/*.test.js,.github/workflows/**,coverage/**

# Miramos el reporte de cobertura de Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info