name: Pipeline de Integracion Continua

# El servidor se activa automáticamente con cada push o merge a la rama main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona el código de tu repositorio en el servidor de IC
    - name: Clonar el repositorio
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    #2. Mover a "In Progress"
    - name: Mover a En Proceso
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%B)
        CARD_ID=$(echo "$COMMIT_MSG" | grep -oE '\[[a-zA-Z0-9]+\]' | sed 's/[][]//g')
        if [ ! -z "$CARD_ID" ]; then
          curl -X PUT -d "idList=6a15d9e8ac4f65852ecd9c15" \
            -d "key=${{ secrets.TRELLO_API_KEY }}" -d "token=${{ secrets.TRELLO_API_TOKEN }}" \
            "https://api.trello.com/1/cards/$CARD_ID"
        fi


    # 3. Instala Node.js en el servidor para usar npm
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 4. Instala las dependencias exactamente como están en tu package.json
    - name: Instalar dependencias
      run: npm ci --ignore-scripts

    #5. Mover a "Testing/CI"
    - name: Mover a Testing/CI
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%B)
        CARD_ID=$(echo "$COMMIT_MSG" | grep -oE '\[[a-zA-Z0-9]+\]' | sed 's/[][]//g')
        if [ ! -z "$CARD_ID" ]; then
          curl -X PUT -d "idList=6a15d9ee66a5fd2aae57ca07" \
            -d "key=${{ secrets.TRELLO_API_KEY }}" -d "token=${{ secrets.TRELLO_API_TOKEN }}" \
            "https://api.trello.com/1/cards/$CARD_ID"
        fi

    # 6. Ejecuta la prueba automatizada que acabamos de probar en local
    - name: Ejecutar pruebas automatizadas
      run: npm test

    # 7. Ejecuta la inspección de código automatizada (SonarCloud)
    - name: SonarQube Cloud Scan
      uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # 8. Mover "Done"
    - name: Mover a Done
      if: success()
      run: |
        # Obtenemos el mensaje de forma robusta con Git log
        COMMIT_MSG=$(git log -1 --pretty=%B)
        
        # Extrae el texto entre corchetes del commit (ej: [c205bf])
        CARD_ID=$(echo "$COMMIT_MSG" | grep -oE '\[[a-zA-Z0-9]+\]' | sed 's/[][]//g')
        
        if [ -z "$CARD_ID" ]; then
          echo "No se encontró ID de Trello en el mensaje del commit. Se saltea el movimiento."
        else
          echo "Moviendo la tarjeta de Trello con ID: $CARD_ID a la columna Done"
          
          # Petición CURL nativa a la API oficial de Trello para mover la tarjeta
          curl -X PUT \
            -d "idList=6a15d9f22be478c39b887d20" \
            -d "key=${{ secrets.TRELLO_API_KEY }}" \
            -d "token=${{ secrets.TRELLO_API_TOKEN }}" \
            "https://api.trello.com/1/cards/$CARD_ID"
        fi

    # 9. Mover a "Fail"
    - name: Mover a Fail
      if: failure()
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%B)
        CARD_ID=$(echo "$COMMIT_MSG" | grep -oE '\[[a-zA-Z0-9]+\]' | sed 's/[][]//g')
        
        if [ ! -z "$CARD_ID" ]; then
          echo "¡Alerta! El pipeline falló. Moviendo la tarjeta con ID: $CARD_ID a la columna de Error."
          curl -X PUT \
            -d "idList=6a2f36483266de0fb2b63935" \
            -d "key=${{ secrets.TRELLO_API_KEY }}" \
            -d "token=${{ secrets.TRELLO_API_TOKEN }}" \
            "https://api.trello.com/1/cards/$CARD_ID"
        fi

    # 10. Desplegar en Render
    - name: Ejecutar Despliegue Continuo en Render
      if: success()
      run: |
        echo "¡Filtros de calidad aprobados! Notificando a Render para iniciar el despliegue..."
        curl -X GET "${{ secrets.RENDER_DEPLOY_HOOK }}"